In [2]:
import torch

In [8]:
a = torch.Tensor([1, 2, 3])
print(a)
print(a.shape)

tensor([1., 2., 3.])
torch.Size([3])


In [11]:
b = torch.ones(2, 3)  # A tensor full of 1.
print(b)
print(b.shape)

print(len(b))  # First dimension.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
2


In [13]:
c = torch.zeros(4, 2, 2)  # A tensor full of 0.
print(c)
print(c.shape)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([4, 2, 2])
4


In [15]:
d = torch.rand(2, 2)  # Normal Distribution with mean = 0, standard deviation = 1.
print(type(d))
print(d)

<class 'torch.Tensor'>
tensor([[0.7553, 0.2506],
        [0.6321, 0.7473]])


In [23]:
e = torch.randint(5, size=(4,3))  # Random value between [0, 5).
print(e)

e = e.reshape(3, -1)
print(e)

tensor([[1, 2, 2],
        [4, 0, 4],
        [3, 2, 1],
        [3, 0, 0]])
tensor([[1, 2, 2, 4],
        [0, 4, 3, 2],
        [1, 3, 0, 0]])


In [9]:
f = torch.arange(6).reshape(2, 3)  # Shape: [2, 3]
g = torch.arange(6).reshape(2, 3)  # Shape: [2, 3]
print(g)

h = torch.cat((f, g), dim=0)
print(h)
print(h.shape)  # Shape: [4, 3]

i = torch.cat((f, g), dim=1)
print(i)
print(i.shape)  # Shape: [2, 6]

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
torch.Size([4, 3])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
torch.Size([2, 6])
