In [1]:
import torch

## Create Tensor

In [ ]:
a = torch.Tensor([1, 2, 3])  # Most common way to create tensor.

b = torch.ones(2, 3)  # A tensor full of 1.

c = torch.zeros(4, 2, 2)  # A tensor full of 0.

d = torch.rand(2, 2)  # Normal Distribution with mean = 0, standard deviation = 1.

e = torch.randint(5, size=(4, 3))  # Random value between [0, 5).

## Shape of Tensor

In [8]:
a = torch.Tensor([1, 2, 3])  # [3]
print(a)
print(a.shape)

tensor([1., 2., 3.])
torch.Size([3])


In [11]:
b = torch.ones(2, 3)  # A tensor full of 1.
print(b)
print(b.shape)

print(len(b))  # First dimension.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
2


In [7]:
c = torch.zeros(4, 2, 2)  # A tensor full of 0.
print(c)
print(c.shape)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([4, 2, 2])


In [8]:
d = torch.rand(2, 2)  # Normal Distribution with mean = 0, standard deviation = 1.
print(d)

tensor([[0.3465, 0.5039],
        [0.9091, 0.6859]])


In [23]:
e = torch.randint(5, size=(4, 3))  # Random value between [0, 5).
print(e)

e = e.reshape(3, -1)
print(e)

tensor([[1, 2, 2],
        [4, 0, 4],
        [3, 2, 1],
        [3, 0, 0]])
tensor([[1, 2, 2, 4],
        [0, 4, 3, 2],
        [1, 3, 0, 0]])


## Usage of `torch.cat()`

In [3]:
f = torch.arange(6).reshape(2, 3)  # shape: [2, 3]
g = torch.arange(6).reshape(2, 3)  # shape: [2, 3]
print("g: ", g)

h = torch.cat((f, g), dim=0)  # [2+2, 3]
print("h: ", h)
print(h.shape)  # shape: [4, 3]

i = torch.cat((f, g), dim=1)  # [2, 3+3]
print("i: ", i)
print(i.shape)  # shape: [2, 6]

g:  tensor([[0, 1, 2],
        [3, 4, 5]])
h:  tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
torch.Size([4, 3])
i:  tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
torch.Size([2, 6])


In [6]:
a = torch.arange(6).reshape(2, 3)  # shape: [2, 3]
b = torch.arange(8).reshape(2, 4)  # shape: [2, 4]

#! c = torch.cat((a, b), dim=0)
# Raise error, Sizes of tensors a and b must match except in dimension 0.

## Usage of `torch.flatten()`

In [11]:
# Range to flatten: [start_dim, end_dim]

t = torch.tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])  # shape: [2, 2, 2]
t1 = torch.flatten(t)
print(t1.shape)  # [8]

t2 = torch.flatten(t, start_dim=1)
print(t2.shape)  # [2, 3]

torch.Size([8])
torch.Size([2, 4])


In [16]:
u = torch.ones(2, 3, 4, 5, 6)

u1 = torch.flatten(u)  # [720]
print(u1.shape)

u2 = torch.flatten(u, start_dim=2)  # [2, 3, 120]
print(u2.shape)

u3 = torch.flatten(u, end_dim=3)  # [120, 6]
print(u3.shape)

u4 = torch.flatten(u, start_dim=2, end_dim=3)  # [2, 3, 20, 6]
print(u4.shape)

torch.Size([720])
torch.Size([2, 3, 120])
torch.Size([120, 6])
torch.Size([2, 3, 20, 6])


## Typecasting of Tensor

In [4]:
# Learn more about data type of tensor: 
# https://pytorch.org/docs/stable/tensors.html#data-types

j = torch.Tensor([1, 2, 3])  # FloatTensor (Default)
print(j.type())

j = j.to(torch.uint8)  # to()
print(j.type())

torch.FloatTensor
torch.ByteTensor
